module.exports = {
	'env': {
		'browser': true,
		'commonjs': true,
		'es6': true,
		'node': true
	},
	'extends': 'eslint:recommended',
	'globals': {
		'Atomics': 'readonly',
		'SharedArrayBuffer': 'readonly'
	},
	'parserOptions': {
		'ecmaVersion': 2018,
		
	},
  "ecmaFeatures": {
    "arrowFunctions": true,
    "blockBindings": true,
    "classes": true,
    "defaultParameters": true,
    "destructuring": true,
    "forOf": true,
    "generators": true,
    "modules": true,
    "objectLiteralComputedProperties": true,
    "objectLiteralDuplicateProperties": true,
    "objectLiteralShorthandMethods": true,
    "objectLiteralShorthandProperties": true,
    "regexUFlag": true,
    "regexYFlag": true,
    "restParams": true,
    "spread": true,
    "superInFunctions": true,
    "templateStrings": true,
    "unicodeCodePointEscapes": true,
    "globalReturn": true
  },
  "rules": {
    "comma-dangle": [ "error", "never" ],
    "no-console": "warn",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "warn",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty-character-class": "error",
    "no-empty": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-semi": "error",
    "no-func-assign": "error",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-negated-in-lhs": "error",
    "no-unreachable": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "accessor-pairs": "error",
    "block-scoped-var": "error",
    "curly": "error",
    "default-case": "error",
    "dot-location": [ "error", "property" ],
    "dot-notation": "error",
    "eqeqeq": [ "error", "smart" ],
    "no-alert": "warn",
    "no-caller": "error",
    "no-case-declarations": "error",
    "no-div-regex": "warn",
    "no-else-return": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-implied-eval": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-native-reassign": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-new": "error",
    "no-octal-escape": "error",
    "no-octal": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-redeclare": "error",
    "no-return-assign": "error",
    "no-self-compare": "error",
    "no-throw-literal": "error",
    "no-unused-expressions": [ "error", { "allowShortCircuit": true } ],
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-void": "error",
    "no-warning-comments": "warn",
    "no-with": "error",
    "radix": [ "error", "as-needed" ],
    "vars-on-top": "error",
    "wrap-iife": [ "error", "inside" ],
    "yoda": "error",
    "strict": [ "error", "never" ],
    "no-catch-shadow": "off",
    "no-delete-var": "error",
    "no-shadow-restricted-names": "error",
    "no-shadow": "error",
    "no-undef-init": "error",
    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
    "no-use-before-define": "error",
    "global-require": "error",
    "handle-callback-err": "warn",
    "no-new-require": "error",
    "array-bracket-spacing": [ "error", "never" ],
    "block-spacing": [ "error", "always" ],
    "brace-style": [ "error", "1tbs", { "allowSingleLine": false } ],
    "camelcase": [ "error", { "properties": "always" } ],
    "comma-spacing": [ "error", { "before": false, "after": true } ],
    "comma-style": [ "error", "last" ],
    "computed-property-spacing": [ "error", "always" ],
    "consistent-this": [ "error", "self" ],
    "eol-last": "error",
    "func-style": [ "error", "declaration", { "allowArrowFunctions": true } ],
    "indent": [ "error", 2, { "SwitchCase": 1 } ],
    "key-spacing": [ "error", { "beforeColon": false, "afterColon": true } ],
    "new-cap": "error",
    "new-parens": "error",
    // "newline-after-var": [ "error", "never" ],
    "no-array-constructor": "error",
    "no-bitwise": "error",
    "no-continue": "error",
    "no-lonely-if": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multiple-empty-lines": [ "error", { "max": 2, "maxEOF": 1 } ],
    "no-nested-ternary": "error",
    "no-new-object": "error",
    "no-spaced-func": "error",
    "no-trailing-spaces": [ "error", { "skipBlankLines": true } ],
    "no-unneeded-ternary": "error",
    "object-curly-spacing": [ "error", "always" ],
    // "one-var": [ "error", "always" ],
    "operator-linebreak": [ "error", "none" ],
    "quote-props": [ "error", "as-needed" ],
    "quotes": [ "error", "double", "avoid-escape" ],
    "semi": [ "error", "always" ],
    "keyword-spacing": [ "error", { "before": true, "after": true }],
    "space-before-blocks": [ "error", "always" ],
    "space-before-function-paren": [ "error", "never" ],
    "space-in-parens": [ "error", "never" ],
    "space-infix-ops": "error",
    "space-unary-ops": [ "error", { "words": true, "nonwords": false } ],
    "spaced-comment": [ "error", "always" ],
    "arrow-parens": [ "error", "as-needed" ],
    "arrow-spacing": "error",
    "constructor-super": "error",
    "generator-star-spacing": [ "error", { "before": true, "after": false } ],
    "no-confusing-arrow": "warn",
    "no-class-assign": "error",
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-this-before-super": "error",
    "no-var": "error",
    "prefer-arrow-callback": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "require-yield": "error"
  }
}